### ISSUE TITLE
AssertionError on roles: in playbook

### ISSUE THREAD

**Issue by mikebell** [willthames/ansible-lint#67] opened 2015-08-13 10:40 UTC
I've updated ansible-lint using pip:
```
sudo pip install ansible-lint --upgrade
```
Still getting the same error but different lines in the source code now.

```
mbell@Michaels-MacBook-Pro-2 [11:35:18] [~/Vagrant/drupaldev-vm] [dev *]
-> % ansible-lint --version
ansible-lint 2.1.0
mbell@Michaels-MacBook-Pro-2 [11:35:25] [~/Vagrant/drupaldev-vm] [dev *]
-> % ansible-lint provisioning/playbook.yml
Traceback (most recent call last):
  File "/usr/local/bin/ansible-lint", line 110, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/bin/ansible-lint", line 97, in main
    matches = runner.run()
  File "/Library/Python/2.7/site-packages/ansiblelint/__init__.py", line 178, in run
    skip_tags=set(self.skip_tags)))
  File "/Library/Python/2.7/site-packages/ansiblelint/__init__.py", line 112, in run
    matches.extend(rule.matchtasks(playbookfile, text))
  File "/Library/Python/2.7/site-packages/ansiblelint/__init__.py", line 59, in matchtasks
    for task in ansiblelint.utils.get_action_tasks(yaml, file):
  File "/Library/Python/2.7/site-packages/ansiblelint/utils.py", line 254, in get_action_tasks
    if 'include' not in task.keys()]
  File "/Library/Python/2.7/site-packages/ansiblelint/utils.py", line 227, in normalize_task
    assert False
AssertionError
```

```
---
- hosts: all
  sudo: yes
  vars_files:
    - "./vars/main.yml"
    - "./vars/sites.yml"
  tasks:
    - name: register rvm
      stat: path=/home/vagrant/.rvm
      register: rvmpath
    - name: install python-pycurl
      apt: pkg=python-pycurl state=latest
    - name: Create ssh config file
      template: src=../files/config dest=/home/vagrant/.ssh/config owner=vagrant group=vagrant mode=0644
    - name: Create Databases
      mysql_db: name={{ item }} state=present login_user="root" login_password={{ mariadb_root_password }}
      with_items: mysql_dbs.keys()
      tags: db
    - name: Create DB Users
      mysql_user: name={{ item.value.user }} password={{ item.value.pass }} priv="{{ item.key }}.*:ALL" login_user="root" login_password={{ mariadb_root_password }}
      tags: db
      with_dict: mysql_dbs
  roles:
    - common
    - { role: ansible-mariadb55 }
    - { role: jdauphant.nginx, tags: nginx }
    - { role: geerlingguy.php }
    - { role: geerlingguy.drush }
    - { role: geerlingguy.java }
    - { role: geerlingguy.solr }
    - { role: geerlingguy.php-xdebug, php_xdebug_max_nesting_level: 256}
    - { role: geerlingguy.mailhog }
  handlers:
    - name: update repositories
      apt: update_cache=yes cache_valid_time=3600
```

**Comment by mikebell** [comment] 2015-08-13 20:54
@willthames Thanks for the update to ansible-lint here is the new debug output from source:

```
digital@hellstorm [09:52:48] [~/Vagrant/drupaldev-vm] [dev]
-> % ansible-lint --version
ansible-lint 2.1.1
digital@hellstorm [09:52:51] [~/Vagrant/drupaldev-vm] [dev]
-> % ansible-lint provisioning/playbook.yml 
Was not expecting value [{'apt': 'name={{ item }} state=latest', 'name': 'Install Packages', '__line__': 5, 'with_items': ['git', 'htop', 'graphviz']}, {'shell': 'locale-gen en_GB.UTF-8', 'name': 'set language pack', '__line__': 11}, {'apt': 'update_cache=yes cache_valid_time=3600', 'name': 'Update apt cache', '__line__': 13}] of type <type 'list'> for key tasks
Task: {'hosts': 'all', 'tasks': [{'apt': 'name={{ item }} state=latest', 'name': 'Install Packages', '__line__': 5, 'with_items': ['git', 'htop', 'graphviz']}, {'shell': 'locale-gen en_GB.UTF-8', 'name': 'set language pack', '__line__': 11}, {'apt': 'update_cache=yes cache_valid_time=3600', 'name': 'Update apt cache', '__line__': 13}], 'sudo': True, '__line__': 2}
```

**Comment by willthames** [comment] 2015-08-14 09:54
@mikebell ansible-lint checks the included roles too, which explains why it's looking in that file. Could you provide the contents of that file (or even better a link to the source for the role if it's not got anything private in it) so that I can do some more digging?

**Comment by mikebell** [comment] 2015-08-14 10:09
It's all public at https://github.com/mikebell/drupaldev-vm

**Comment by willthames** [comment] 2015-08-14 10:30
Ok, I still can't reproduce! Even after running `ansible-galaxy install -r provisioning/requirements.txt -p provisioning/roles`

Can you confirm the version of ansible you're using too please?

**Comment by shaleh** [comment] 2015-08-14 17:05
I can confirm that running from pip and from GitHub do not have the AssertError.

**Comment by willthames** [comment] 2016-01-18 10:34
Closing, can't reproduce.

**Closed by willthames** 2016-01-18 10:34 UTC
